Repository oncokb/matchminer-curate, pull requests merged in 2018-04, with the labels that each got.

#58 replace firestore with firebase realtime db and update data sharing between components
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/arm/arm.component.ts
  src/main/webapp/app/arm/arm.model.ts
  src/main/webapp/app/clinical/clinical.component.html
  src/main/webapp/app/clinical/clinical.component.ts
  src/main/webapp/app/clinical/clinical.model.ts
  src/main/webapp/app/environments/environment.example.ts
  src/main/webapp/app/genomic/genomic.component.html
  src/main/webapp/app/genomic/genomic.component.ts
  src/main/webapp/app/genomic/genomic.model.ts
  src/main/webapp/app/layouts/main/main.component.html
  src/main/webapp/app/layouts/main/main.component.ts
  src/main/webapp/app/login/login.component.ts
  src/main/webapp/app/match/match.component.html
  src/main/webapp/app/match/match.component.ts
  src/main/webapp/app/panel/movingPath.model.ts
  src/main/webapp/app/panel/panel.component.ts
  src/main/webapp/app/service/trial.service.ts
  src/main/webapp/app/trial/trial.component.html
  src/main/webapp/app/trial/trial.component.ts
Labels: DO NOT MERGE, Interface, enhancement, ready to review

#60 update genomic and clinical data format
  src/main/webapp/app/genomic/genomic.component.html
  src/main/webapp/app/genomic/genomic.component.ts
  src/main/webapp/app/genomic/genomic.model.ts
  src/main/webapp/app/panel/panel.component.ts
  src/main/webapp/app/service/trial.service.ts
  src/main/webapp/app/trial/trial.component.html
  src/main/webapp/app/trial/trial.component.ts
  src/main/webapp/app/trial/trial.model.ts
Labels: Interface, ready to review

#66 synchronize data
  src/main/webapp/app/service/trial.service.ts
Labels: bug

#67 display trials in table and add archive option
  package-lock.json
  package.json
  src/main/webapp/app/app.module.ts
  src/main/webapp/app/service/trial.service.ts
  src/main/webapp/app/trial/trial.component.html
  src/main/webapp/app/trial/trial.component.ts
  src/main/webapp/app/trial/trial.model.ts
  src/main/webapp/app/trial/trial.scss
Labels: Interface, enhancement

#74 Cannot add arm
  src/main/webapp/app/match/match.component.html
  src/main/webapp/app/service/trial.service.ts
Labels: ready to review

#75 Add empty check for newly added genomic and clinical nodes
  src/main/webapp/app/genomic/genomic.component.ts
  src/main/webapp/app/panel/panel.component.ts
Labels: ready to review

#78 return boolean as result for check fields functions
  src/main/webapp/app/panel/panel.component.ts
Labels: ready to review

#80 Add empty check before save
  src/main/webapp/app/panel/panel.component.ts
Labels: ready to review
